<?xml version="1.0"?>
<testsuites>

<testsuite name="Root Suite" timestamp="2023-05-21T15:36:23" tests="0" file="cypress/e2e/firstTest.cy.ts" time="0.000" failures="0"></testsuite>
<testsuite name="Test with backend" timestamp="2023-05-21T15:36:23" tests="5" time="36.207" failures="0">
  
  <testcase name="Test with backend verify correct request and response" time="5.688" classname="verify correct request and response"></testcase>
  
  <testcase name="Test with backend intercepting and modifying the request and response" time="3.697" classname="intercepting and modifying the request and response"></testcase>
  
  <testcase name="Test with backend verify popular tags are displayed" time="2.290" classname="verify popular tags are displayed"></testcase>
  
  <testcase name="Test with backend verify global feed like count" time="7.401" classname="verify global feed like count"></testcase>
  
  <testcase name="Test with backend delete new article in a global feed" time="16.925" classname="delete new article in a global feed"></testcase>
  
</testsuite>

<testsuite name="Root Suite" timestamp="2023-05-21T15:37:04" tests="0" file="cypress/e2e/secondTest.cy.ts" time="0.000" failures="0"></testsuite>
<testsuite name="Test log out" timestamp="2023-05-21T15:37:04" tests="1" time="20.444" failures="1">
  
  <testcase name="Test log out verify use can log out successfully" time="6.422" classname="verify use can log out successfully">
    
    <failure message="Timed out retrying after 4000ms: expected &apos;&lt;ul.nav.navbar-nav.pull-xs-right&gt;&apos; to contain &apos;Sign up1&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected '<ul.nav.navbar-nav.pull-xs-right>' to contain 'Sign up1'
    at Context.eval (webpack:///./cypress/e2e/secondTest.cy.ts:9:26)]]></failure>
    
  </testcase>
  
</testsuite>

</testsuites>